serverConf:
  name: "courseSystem"
  version: "0.0.1"
  host: "0.0.0.0"
  port: 8080
mysqlConf:
  user: "root"
  password: "123456"
  host: "127.0.0.1"
  port: 3306
  db: "courseSystem"
redisConf:
  host: ""
  db: 1
  password: ""